// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBaseError creates a new instance of MockBaseError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseError {
	mock := &MockBaseError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseError is an autogenerated mock type for the BaseError type
type MockBaseError struct {
	mock.Mock
}

type MockBaseError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBaseError) EXPECT() *MockBaseError_Expecter {
	return &MockBaseError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockBaseError
func (_mock *MockBaseError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBaseError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockBaseError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockBaseError_Expecter) Error() *MockBaseError_Error_Call {
	return &MockBaseError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockBaseError_Error_Call) Run(run func()) *MockBaseError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBaseError_Error_Call) Return(s string) *MockBaseError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBaseError_Error_Call) RunAndReturn(run func() string) *MockBaseError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// GetCode provides a mock function for the type MockBaseError
func (_mock *MockBaseError) GetCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockBaseError_GetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCode'
type MockBaseError_GetCode_Call struct {
	*mock.Call
}

// GetCode is a helper method to define mock.On call
func (_e *MockBaseError_Expecter) GetCode() *MockBaseError_GetCode_Call {
	return &MockBaseError_GetCode_Call{Call: _e.mock.On("GetCode")}
}

func (_c *MockBaseError_GetCode_Call) Run(run func()) *MockBaseError_GetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBaseError_GetCode_Call) Return(n int) *MockBaseError_GetCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBaseError_GetCode_Call) RunAndReturn(run func() int) *MockBaseError_GetCode_Call {
	_c.Call.Return(run)
	return _c
}
