// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helper

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIUtilities creates a new instance of MockIUtilities. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUtilities(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUtilities {
	mock := &MockIUtilities{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUtilities is an autogenerated mock type for the iUtilities type
type MockIUtilities struct {
	mock.Mock
}

type MockIUtilities_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUtilities) EXPECT() *MockIUtilities_Expecter {
	return &MockIUtilities_Expecter{mock: &_m.Mock}
}

// GetClientIP provides a mock function for the type MockIUtilities
func (_mock *MockIUtilities) GetClientIP(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClientIP")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIUtilities_GetClientIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientIP'
type MockIUtilities_GetClientIP_Call struct {
	*mock.Call
}

// GetClientIP is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUtilities_Expecter) GetClientIP(ctx interface{}) *MockIUtilities_GetClientIP_Call {
	return &MockIUtilities_GetClientIP_Call{Call: _e.mock.On("GetClientIP", ctx)}
}

func (_c *MockIUtilities_GetClientIP_Call) Run(run func(ctx context.Context)) *MockIUtilities_GetClientIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUtilities_GetClientIP_Call) Return(s string) *MockIUtilities_GetClientIP_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIUtilities_GetClientIP_Call) RunAndReturn(run func(ctx context.Context) string) *MockIUtilities_GetClientIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAgent provides a mock function for the type MockIUtilities
func (_mock *MockIUtilities) GetUserAgent(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAgent")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIUtilities_GetUserAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAgent'
type MockIUtilities_GetUserAgent_Call struct {
	*mock.Call
}

// GetUserAgent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUtilities_Expecter) GetUserAgent(ctx interface{}) *MockIUtilities_GetUserAgent_Call {
	return &MockIUtilities_GetUserAgent_Call{Call: _e.mock.On("GetUserAgent", ctx)}
}

func (_c *MockIUtilities_GetUserAgent_Call) Run(run func(ctx context.Context)) *MockIUtilities_GetUserAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUtilities_GetUserAgent_Call) Return(s string) *MockIUtilities_GetUserAgent_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIUtilities_GetUserAgent_Call) RunAndReturn(run func(ctx context.Context) string) *MockIUtilities_GetUserAgent_Call {
	_c.Call.Return(run)
	return _c
}
