package configs

const (
	DEFAULT_CONFIG_FILE = "config.yaml"
	CONFIG_FILE_KEY     = "CONFIG_FILE"

	DEFAULT_SECRET_PATH = "/vault/secrets/config.json"
	SECRET_FILE_KEY     = "SECRET_FILE"
	DATABASE_KEY        = "DATABASE_URL"
	REDIS_KEY           = "REDIS_URL"
	JWT_SECRET_KEY      = "JWT_SECRET"

	DEFAULT_KONG_HEADER_USER_ID   = "X-User-ID"
	DEFAULT_KONG_HEADER_TENANT_ID = "X-Tenant-ID"
	DEFAULT_KONG_HEADER_ROLES     = "X-Roles"

	DEFAULT_SUPER_ADMIN_ROLE = "super-admin"
)
